# Generated by Django 5.1.5 on 2025-01-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeaAPIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=80, unique=True)),
                ('port', models.IntegerField(default=8000)),
                ('service', models.CharField(choices=[('dhcp4', 'DHCPv4'), ('dhcp6', 'DHCPv6')], max_length=5)),
            ],
        ),
    ]
