services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net

  api:
    build: .
    ports:
      - "8000:8000"
    networks:
      - redis-net
    volumes:
      - api_data:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

volumes:
   api_data:
     name: "net2d-api"

networks:
  redis-net:
    driver: bridge
