# Generated by Django 5.1.5 on 2025-02-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='netbox-lab', max_length=30)),
                ('type', models.CharField(default='netbox', max_length=30)),
                ('url', models.CharField(default='http://192.168.1.0:8080/', max_length=80)),
                ('token', models.CharField(default='0123456789abcdef0123456789abcdef01234567', max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
