# Generated by Django 5.1.5 on 2025-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sot',
            name='name',
            field=models.CharField(default='netbox-lab', max_length=30, unique=True),
        ),
    ]
