# Generated by Django 5.1.5 on 2025-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sot',
            name='url',
        ),
        migrations.AddField(
            model_name='sot',
            name='hostname',
            field=models.CharField(default='143.54.235.23', max_length=80),
        ),
        migrations.AddField(
            model_name='sot',
            name='port',
            field=models.IntegerField(default=8080),
        ),
    ]
