# Generated by Django 5.1.5 on 2025-03-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sot_url_sot_hostname_sot_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sot',
            name='hostname',
            field=models.CharField(default='192.168.3.105', max_length=80),
        ),
    ]
